containers :
	$(MAKE) -C shared container
	$(MAKE) -C api container
	$(MAKE) -C base container
	$(MAKE) -C entry-cache container
	$(MAKE) -C entry-store container
	$(MAKE) -C fanout container
	$(MAKE) -C follow container
	$(MAKE) -C front container
	$(MAKE) -C home container
	$(MAKE) -C index container
	$(MAKE) -C mine container
	$(MAKE) -C post container
	$(MAKE) -C repl container
	$(MAKE) -C reserve container
	$(MAKE) -C search container
	$(MAKE) -C timeline container
	$(MAKE) -C timeline-shard container
	$(MAKE) -C monitor container

.PHONY : containers
